modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/LoveTropics/GamemodeBuild"
license="Mozilla Public License Version 2.0"

[[mods]]
modId="gamemodebuild"
version="$mod_version"
displayName="Gamemode Build"
credits=""
authors="tterrag, Gegy"
description='''
Creative mode without creative. Great for collaborative public building.
'''

[[dependencies.gamemodebuild]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gamemodebuild]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="gamemodebuild.mixins.json"
